apiVersion: v1
kind: Service
metadata:
  name: provisioner-personalmappe
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    io.kompose.service: provisioner-personalmappe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provisioner-personalmappe
  labels:
    io.kompose.service: provisioner-personalmappe
spec:
  selector:
    matchLabels:
      io.kompose.service: provisioner-personalmappe
  template:
    metadata:
      labels:
        io.kompose.service: provisioner-personalmappe
    spec:
      containers:
        - name: provisioner-personalmappe
          image: fintlabs.azurecr.io/provisioner-personalmappe:build.1
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
            requests:
              cpu: "250m"
              memory: "1Gi"
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /tjenester/personalmappe/actuator/health
          env:
            - name: TZ
              value: Europe/Oslo
            - name: JAVA_TOOL_OPTIONS
                value: -XX:+ExitOnOutOfMemoryError -Xmx1G
            - name: spring.security.oauth2.client.registration.rogfk.client-id
              valueFrom:
                secretKeyRef:
                  key: client-id
                  name: kulturtanken-rogaland
            - name: spring.security.oauth2.client.registration.rogfk.client-secret
              valueFrom:
                secretKeyRef:
                  key: client-secret
                  name: kulturtanken-rogaland
            - name: fint.organisations.rogfk.username
              valueFrom:
                secretKeyRef:
                  name: kulturtanken-rogaland
                  key: username
            - name: fint.organisations.rogfk.password
              valueFrom:
                secretKeyRef:
                  name: kulturtanken-rogaland
                  key: password
            - name: spring.data.mongodb.uri
              valueFrom:
                secretKeyRef:
                  name: fint-mongo
                  key: mongodb
            - name: spring.data.mongodb.database
              value: provisioner-personalmappe
