apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ofk-no

resources:
  - ../../../base
  - onepassword.yaml
  - fint-client.yaml

commonLabels:
  app.kubernetes.io/instance: provisioner-personalmappe_ofk-no
  fintlabs.no/org-id: ofk.no

patches:

  - target:
      kind: Deployment
      name: provisioner-personalmappe
    path: deployment.yaml