apiVersion: v1
kind: Service
metadata:
  name: provisioner-personalmappe-viken
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    io.kompose.service: provisioner-personalmappe-viken